In [312]:
import pandas as pd
import numpy as np
import math

pd.set_option('display.max_columns', None)

## Example

In [97]:
pd.read_csv('data/MOL-HRM-Information.csv')

,TITLE,DESCRIPTION,FILE,YOUTUE
0,Title1,AABBCC,download/article/article_20151006152249.pdf,https://www.youtube.com/watch?v=Zwq-T5esX_Y&fe...
1,Title2,"Desc2,AABB",download/article/article_20151006152249.pdf,https://www.youtube.com/watch?v=Zwq-T5esX_Y&fe...
2,Title3,Desc3,download/article/article_20151006152249.pdf,https://www.youtube.com/watch?v=Zwq-T5esX_Y&fe...
3,title4,"AABB,AABB",download/article/article_20151006152249.pdf,https://www.youtube.com/watch?v=Zwq-T5esX_Y&fe...

# 2 phtloc

In [98]:
ar_group2 = pd.read_csv('data/2_phtloc/article_group.csv')
ar_list2 = pd.read_csv('data/2_phtloc/article_list.csv')
ar_detail2 = pd.read_csv('data/2_phtloc/article_detail.csv')

In [99]:
print(ar_group2.shape)
ar_group2.head()

(15, 13)

,c_id,c_name,c_rss,c_parent,c_show_search,c_show_sub,c_show_pic,c_show_date,c_show_detail,c_show_subnew,c_type,d_id,d_id_w3c
0,2,เกี่ยวกับศูนย์ CCPL,NaN,0,NaN,Y,images/design2015/icon_list.png,NaN,NaN,NaN,NaN,6,0
1,3,สาระเรื่องค้ามนุษย์,NaN,0,NaN,Y,images/bullet/bullet01.jpg,NaN,NaN,NaN,NaN,6,0
2,4,กฎหมาย/ระเบียบที่เกี่ยวข้อง,NaN,0,NaN,Y,images/bullet/bullet01.jpg,NaN,NaN,NaN,NaN,6,0
3,5,ผลการดำเนินงาน,NaN,0,NaN,Y,NaN,NaN,NaN,NaN,NaN,6,0
4,6,การประชุม/สัมมนา,NaN,0,NaN,Y,@detail_news#,NaN,NaN,NaN,NaN,6,0

In [152]:
print(ar_list2.shape)
print(np.unique(ar_list2['n_id']).shape)
print(np.unique(ar_list2['c_id']).shape)
ar_list2.head()

(441, 49)
(441,)
(13,)

,n_id,c_id,n_date,n_new_modi,n_last_modi,n_timestamp,n_topic,n_des,source,sourceLink,keyword,picture,news_use,at_id,d_id,link_html,target,expire,logo,access,n_share,n_shareuse,n_sharename,n_shareid,n_approve,n_approvedate,for_pda,show_newstop,show_vote,show_comment,comment_type,n_owner,n_date_start,n_date_end,n_time,n_delowner,n_deldate,show_group,show_topic,show_date,n_owner_org,show_textsize,show_count,d_id_w3c,picture_alt,html,wcag,css,youtube
0,2,2,2558-11-17,20151116101602,20171020100723,2016-03-10 16:49:36,ศูนย์ CCPL,NaN,NaN,NaN,NaN,NaN,2,10,0,NaN,_self,2558-11-21,NaN,NaN,NaN,NaN,NaN,NaN,Y,2018-06-05,NaN,NaN,NaN,NaN,1.0,0,NaN,NaN,NaN,NaN,NaN,1.0,1,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,False
1,3,2,2558-11-15,20151116101630,20151120112324,2015-11-16 10:16:30,วัตถุประสงค์,NaN,NaN,NaN,NaN,NaN,2,10,6,NaN,_self,2558-11-21,NaN,NaN,NaN,NaN,NaN,NaN,Y,2018-06-05,NaN,NaN,NaN,NaN,1.0,0,NaN,NaN,NaN,NaN,NaN,1.0,1,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,False
2,4,2,2558-11-14,20151116101710,20160607115446,2015-11-16 10:17:10,ที่ตั้งศูนย์ PHTLOC,NaN,NaN,NaN,NaN,NaN,2,10,6,NaN,_self,2558-11-21,NaN,NaN,NaN,NaN,NaN,NaN,Y,2018-06-05,NaN,NaN,NaN,NaN,1.0,0,NaN,NaN,NaN,NaN,NaN,1.0,1,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,False
3,5,2,2558-11-13,20151116101734,20151116101734,2015-11-16 10:17:34,พิธีเปิดศูนย์ PHTLOC,NaN,NaN,NaN,NaN,NaN,2,10,6,NaN,_self,2558-11-21,NaN,NaN,NaN,NaN,NaN,NaN,Y,2018-06-05,NaN,NaN,NaN,NaN,1.0,0,NaN,NaN,NaN,NaN,NaN,1.0,1,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,False
4,6,11,2558-11-15,20151116110921,20160806121606,2015-11-16 11:15:24,ส่งมือปราบ มาทำงาน &quot;ต้านค้ามนุษย์&quot;,NaN,NaN,NaN,NaN,NaN,2,10,6,NaN,_self,2558-11-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-06-05,NaN,NaN,NaN,NaN,1.0,0,NaN,NaN,NaN,NaN,NaN,1.0,1,1.0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,False

In [151]:
def getLinkHTML(prefix,link):
    if len(str(link)) > 0:
        if str(link).startswith(prefix):
            return link
        else: 
            return None
    else:
        return None

In [182]:
ar_list2["youtube"] = ar_list2.apply(lambda x: getLinkHTML('https://www.youtube.com/',x["link_html"]), axis = 1)
ar_list2["file"] = ar_list2.apply(lambda x: getLinkHTML('download/',x["link_html"]), axis = 1)

In [183]:
ar_list2.head()

,n_id,c_id,n_date,n_new_modi,n_last_modi,n_timestamp,n_topic,n_des,source,sourceLink,keyword,picture,news_use,at_id,d_id,link_html,target,expire,logo,access,n_share,n_shareuse,n_sharename,n_shareid,n_approve,n_approvedate,for_pda,show_newstop,show_vote,show_comment,comment_type,n_owner,n_date_start,n_date_end,n_time,n_delowner,n_deldate,show_group,show_topic,show_date,n_owner_org,show_textsize,show_count,d_id_w3c,picture_alt,html,wcag,css,youtube,file
0,2,2,2558-11-17,20151116101602,20171020100723,2016-03-10 16:49:36,ศูนย์ CCPL,NaN,NaN,NaN,NaN,NaN,2,10,0,NaN,_self,2558-11-21,NaN,NaN,NaN,NaN,NaN,NaN,Y,2018-06-05,NaN,NaN,NaN,NaN,1.0,0,NaN,NaN,NaN,NaN,NaN,1.0,1,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,None,None
1,3,2,2558-11-15,20151116101630,20151120112324,2015-11-16 10:16:30,วัตถุประสงค์,NaN,NaN,NaN,NaN,NaN,2,10,6,NaN,_self,2558-11-21,NaN,NaN,NaN,NaN,NaN,NaN,Y,2018-06-05,NaN,NaN,NaN,NaN,1.0,0,NaN,NaN,NaN,NaN,NaN,1.0,1,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,None,None
2,4,2,2558-11-14,20151116101710,20160607115446,2015-11-16 10:17:10,ที่ตั้งศูนย์ PHTLOC,NaN,NaN,NaN,NaN,NaN,2,10,6,NaN,_self,2558-11-21,NaN,NaN,NaN,NaN,NaN,NaN,Y,2018-06-05,NaN,NaN,NaN,NaN,1.0,0,NaN,NaN,NaN,NaN,NaN,1.0,1,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,None,None
3,5,2,2558-11-13,20151116101734,20151116101734,2015-11-16 10:17:34,พิธีเปิดศูนย์ PHTLOC,NaN,NaN,NaN,NaN,NaN,2,10,6,NaN,_self,2558-11-21,NaN,NaN,NaN,NaN,NaN,NaN,Y,2018-06-05,NaN,NaN,NaN,NaN,1.0,0,NaN,NaN,NaN,NaN,NaN,1.0,1,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,None,None
4,6,11,2558-11-15,20151116110921,20160806121606,2015-11-16 11:15:24,ส่งมือปราบ มาทำงาน &quot;ต้านค้ามนุษย์&quot;,NaN,NaN,NaN,NaN,NaN,2,10,6,NaN,_self,2558-11-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-06-05,NaN,NaN,NaN,NaN,1.0,0,NaN,NaN,NaN,NaN,NaN,1.0,1,1.0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,None,None

In [184]:
print(ar_detail2.shape)
print(np.unique(ar_detail2['ad_id']).shape)
print(np.unique(ar_detail2['n_id']).shape)
ar_detail2.head()

(3305, 16)
(3305,)
(208,)

,ad_id,n_id,at_type_col,at_type_row,ad_pic_s,ad_pic_h,ad_pic_w,ad_pic_b,ad_des,ad_font,ad_size,ad_bold,ad_italic,ad_color,ad_align,ad_count
0,1,1,1,1,NaN,200,200,NaN,NaN,MS Sans Serif,1,NaN,NaN,#000000,left,0
1,2,2,1,1,NaN,0,0,NaN,"\r\n\r\n<p>\r\n\t\r\n<table style=""WIDTH: 90%;...",NaN,0,NaN,NaN,NaN,NaN,0
2,3,3,1,1,NaN,0,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
3,4,4,1,1,NaN,0,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
4,5,5,1,1,NaN,0,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

In [188]:
result21 = pd.merge(ar_group2, ar_list2, how='left', on=['c_id'])
result21.shape

(437, 62)

In [189]:
result22 = pd.merge(result21, ar_detail2, how='left', on=['n_id'])
result22.shape

(3515, 77)

In [190]:
result22.head()

,c_id,c_name,c_rss,c_parent,c_show_search,c_show_sub,c_show_pic,c_show_date,c_show_detail,c_show_subnew,c_type,d_id_x,d_id_w3c_x,n_id,n_date,n_new_modi,n_last_modi,n_timestamp,n_topic,n_des,source,sourceLink,keyword,picture,news_use,at_id,d_id_y,link_html,target,expire,logo,access,n_share,n_shareuse,n_sharename,n_shareid,n_approve,n_approvedate,for_pda,show_newstop,show_vote,show_comment,comment_type,n_owner,n_date_start,n_date_end,n_time,n_delowner,n_deldate,show_group,show_topic,show_date,n_owner_org,show_textsize,show_count,d_id_w3c_y,picture_alt,html,wcag,css,youtube,file,ad_id,at_type_col,at_type_row,ad_pic_s,ad_pic_h,ad_pic_w,ad_pic_b,ad_des,ad_font,ad_size,ad_bold,ad_italic,ad_color,ad_align,ad_count
0,2,เกี่ยวกับศูนย์ CCPL,NaN,0,NaN,Y,images/design2015/icon_list.png,NaN,NaN,NaN,NaN,6,0,2.0,2558-11-17,2.015112e+13,2.017102e+13,2016-03-10 16:49:36,ศูนย์ CCPL,NaN,NaN,NaN,NaN,NaN,2.0,10.0,0.0,NaN,_self,2558-11-21,NaN,NaN,NaN,NaN,NaN,NaN,Y,2018-06-05,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,None,None,2.0,1.0,1.0,NaN,0.0,0.0,NaN,"\r\n\r\n<p>\r\n\t\r\n<table style=""WIDTH: 90%;...",NaN,0.0,NaN,NaN,NaN,NaN,0.0
1,2,เกี่ยวกับศูนย์ CCPL,NaN,0,NaN,Y,images/design2015/icon_list.png,NaN,NaN,NaN,NaN,6,0,3.0,2558-11-15,2.015112e+13,2.015112e+13,2015-11-16 10:16:30,วัตถุประสงค์,NaN,NaN,NaN,NaN,NaN,2.0,10.0,6.0,NaN,_self,2558-11-21,NaN,NaN,NaN,NaN,NaN,NaN,Y,2018-06-05,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,None,None,3.0,1.0,1.0,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0
2,2,เกี่ยวกับศูนย์ CCPL,NaN,0,NaN,Y,images/design2015/icon_list.png,NaN,NaN,NaN,NaN,6,0,4.0,2558-11-14,2.015112e+13,2.016061e+13,2015-11-16 10:17:10,ที่ตั้งศูนย์ PHTLOC,NaN,NaN,NaN,NaN,NaN,2.0,10.0,6.0,NaN,_self,2558-11-21,NaN,NaN,NaN,NaN,NaN,NaN,Y,2018-06-05,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,None,None,4.0,1.0,1.0,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0
3,2,เกี่ยวกับศูนย์ CCPL,NaN,0,NaN,Y,images/design2015/icon_list.png,NaN,NaN,NaN,NaN,6,0,5.0,2558-11-13,2.015112e+13,2.015112e+13,2015-11-16 10:17:34,พิธีเปิดศูนย์ PHTLOC,NaN,NaN,NaN,NaN,NaN,2.0,10.0,6.0,NaN,_self,2558-11-21,NaN,NaN,NaN,NaN,NaN,NaN,Y,2018-06-05,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,None,None,5.0,1.0,1.0,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0
4,2,เกี่ยวกับศูนย์ CCPL,NaN,0,NaN,Y,images/design2015/icon_list.png,NaN,NaN,NaN,NaN,6,0,38.0,2558-12-16,2.015122e+13,2.015122e+13,2015-12-16 17:21:18,ddd,NaN,NaN,NaN,NaN,NaN,2.0,10.0,0.0,NaN,_blank,2558-12-21,NaN,NaN,NaN,NaN,NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,2.016013e+13,1.0,1.0,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,None,None,442.0,1.0,1.0,NaN,200.0,200.0,NaN,NaN,MS Sans Serif,1.0,NaN,NaN,#000000,left,0.0

In [191]:
only_use_column2 = result22[['c_id','c_name','n_id','n_topic','n_des','ad_des','youtube','file']].groupby(['c_id'])

In [194]:
only_use_column2.get_group(4)

,c_id,c_name,n_id,n_topic,n_des,ad_des,youtube,file
12,4,กฎหมาย/ระเบียบที่เกี่ยวข้อง,105.0,การผ่อนผันให้ผู้เสียสละและพยานในคดีค้ามนุษย์ อ...,NaN,"\r\n\r\n<div align=""center""><span style=""FONT-...",None,None
13,4,กฎหมาย/ระเบียบที่เกี่ยวข้อง,106.0,การผ่อนผันให้ผู้เสียสละและพยานในคดีค้ามนุษย์ อ...,NaN,NaN,None,download/article/article_20160607115820.pdf
14,4,กฎหมาย/ระเบียบที่เกี่ยวข้อง,16.0,พระราชบัญญัติป้องกันและปราบปรามการค้ามนุษย์ พ....,NaN,NaN,None,download/Download/human_trafficking_2551_for19...
15,4,กฎหมาย/ระเบียบที่เกี่ยวข้อง,17.0,พระราชบัญญัติคุ้มครองแรงงาน พ.ศ. 2541 และที่แก...,NaN,NaN,None,download/Download/2labour_2541_for19Nov2015_00...
16,4,กฎหมาย/ระเบียบที่เกี่ยวข้อง,18.0,พระราชบัญญัติการทำงานของคนต่างด้าว พ.ศ. 2551,NaN,NaN,None,download/Download/3Law_doe_2551_for19Nov2015_0...
17,4,กฎหมาย/ระเบียบที่เกี่ยวข้อง,19.0,พระราชบัญญัติเงินทดแทน พ.ศ. 2537,NaN,NaN,None,download/Download/5Law_money_2537_for19Nov2015...
18,4,กฎหมาย/ระเบียบที่เกี่ยวข้อง,20.0,พระราชกำหนดการประมง พ.ศ. 2558,NaN,NaN,None,download/Download/6Law_pramong_2558_for19Nov20...
19,4,กฎหมาย/ระเบียบที่เกี่ยวข้อง,21.0,พระราชบัญญัติแรงงานทางทะเล พ.ศ. 2558,NaN,NaN,None,download/Download/7Law_seaDOE_2558_for19Nov201...
20,4,กฎหมาย/ระเบียบที่เกี่ยวข้อง,22.0,กฎกระทรวงคุ้มครองแรงงานในงานประมงทะเล พ.ศ. 2557,NaN,NaN,None,download/Download/8Law_seaDoe_2557_for19Nov201...
21,4,กฎหมาย/ระเบียบที่เกี่ยวข้อง,23.0,ระเบียบสำนักนายกรัฐมนตรีว่าด้วยมาตรการทางบริหา...,NaN,NaN,None,download/Download/9Law_human_for19Nov2015_001.pdf
22,4,กฎหมาย/ระเบียบที่เกี่ยวข้อง,27.0,ffd,NaN,NaN,None,download/article/article_20151120113416.jpg
23,4,กฎหมาย/ระเบียบที่เกี่ยวข้อง,29.0,พพไไพพพ,NaN,NaN,None,download/article/article_20151120125921.jpg
24,4,กฎหมาย/ระเบียบที่เกี่ยวข้อง,30.0,พระราชบัญญัติจัดหางานและคุ้มครองคนหางาน พ.ศ. 2...,NaN,NaN,None,download/Download/19-20-9999-update.pdf
25,4,กฎหมาย/ระเบียบที่เกี่ยวข้อง,31.0,TEST,NaN,NaN,None,None
26,4,กฎหมาย/ระเบียบที่เกี่ยวข้อง,32.0,พระราชบัญญัติคุ้มครองแรงงาน พ.ศ. 2541 และที่แก...,NaN,NaN,None,download/Download/2labour_2541_for19Nov2015_00...
27,4,กฎหมาย/ระเบียบที่เกี่ยวข้อง,273.0,พระราชกำหนดการบริหารจัดการการทำงานของคนต่างด้า...,NaN,NaN,None,download/article/article_20170622150901.pdf

In [207]:
for group in only_use_column2.groups:
    output_df = pd.DataFrame(columns=['TITLE','DESCRIPTION','FILE','YOUTUBE'])
    output_df['TITLE'] = only_use_column2.get_group(group)['n_topic']
    output_df['DESCRIPTION'] = only_use_column2.get_group(group)['n_des'] + ',' + only_use_column2.get_group(group)['ad_des']
    output_df['FILE'] = only_use_column2.get_group(group)['file']
    output_df['YOUTUBE'] = only_use_column2.get_group(group)['youtube']
#     print(output_df)
    output_df.to_csv('output/2_phtloc/group_id_'+str(group)+'.csv', index=False)

# 6 hrm web

In [313]:
ar_group6 = pd.read_csv('data/6_hrm_web/article_group.csv')
ar_list6 = pd.read_csv('data/6_hrm_web/article_list.csv')
ar_detail6 = pd.read_csv('data/6_hrm_web/article_detail.csv')

## Check Prefix Type

In [246]:
# def getLinkHTML(list_prefix,link):
#     answer = 'no'
#     for prefix in list_prefix:
#         if len(str(link)) > 0:
#             if str(link).startswith(prefix):
#                 answer='yes'
#             else: 
#                 answer= 'yes' if answer == 'yes' else 'no'
#         else:
#             answer= 'yes' if answer == 'yes' else 'no'
#     return link if answer == 'yes' else None

In [333]:
def getLinkHTML(list_of_yes,list_of_no,link):
    answer = 'no'
    for prefix in list_of_yes:
        if len(str(link)) > 0:
            if str(link).startswith(prefix):
                
                # check is in list of no
                ans2 = 'no'
                for prefix2 in list_of_no:
                    if str(link).startswith(prefix2):
                        ans2 = 'yes' 
                    else:
                        ans2 = 'yes' if ans2 == 'yes' else 'no'  
                
                answer = 'yes' if ans2 == 'no' else 'no'
                
            else: 
                answer= 'yes' if answer == 'yes' else 'no'
        else:
            answer= 'yes' if answer == 'yes' else 'no'
    return link if answer == 'yes' else str(float('nan'))

In [334]:
getLinkHTML(['https://','http://'],['https://www.youtube','http://www.youtube'],'https://www.youtube.com')

'nan'

In [335]:
ar_list6["url"] = ar_list6.apply(lambda x: getLinkHTML(['https://','http://'],['https://www.youtube.com/','http://www.youtube.com/'],x["link_html"]), axis = 1)
ar_list6["youtube"] = ar_list6.apply(lambda x: getLinkHTML(['https://www.youtube.com/','http://www.youtube.com/'],[],x["link_html"]), axis = 1)
ar_list6["file"] = ar_list6.apply(lambda x: getLinkHTML(['download/'],[],x["link_html"]), axis = 1)

## Merge & Join

In [336]:
result61 = pd.merge(ar_group6, ar_list6, how='left', on=['c_id'])
result61.shape

(142, 63)

In [337]:
result62 = pd.merge(result61, ar_detail6, how='left', on=['n_id'])
result62.shape

(202, 78)

In [338]:
only_use_column6 = result62[['c_id','c_name','n_id','n_topic','n_des','ad_des','youtube','file','url']].groupby(['c_id'])

In [339]:
# only_use_column6.get_group(4)

## Output Format

In [353]:
def descFormat(title,desc,file,youtube,url):
    if str(desc) != 'nan':
        return desc
    else:
        if str(youtube) != 'nan':
            return '<p>[embed]' + youtube + '[/embed]</p>'
        elif str(url) != 'nan':
            return '<script type="text/javascript">window.location.replace("'+ url +'");</script>'
        elif str(file) != 'nan':
            return title
        else:
            return title

In [354]:
output[8]['TITLE'].values[0]

'ชื่อหน่วยงานใน สป. (อังกฤษ)'

In [355]:
str(output[8]['DESCRIPTION'].values[0])

'nan'

In [356]:
descFormat(output[8]['TITLE'].values[0],output[8]['DESCRIPTION'].values[0],output[8]['FILE'].values[0],output[8]['YOUTUBE'].values[0],output[8]['URL'].values[0])

'ชื่อหน่วยงานใน สป. (อังกฤษ)'

In [359]:
output = list()
for group in only_use_column6.groups:
    output_df = pd.DataFrame(columns=['TITLE','DESCRIPTION','FILE','YOUTUBE'])
    output_df['TITLE'] = only_use_column6.get_group(group)['n_topic']
    output_df['DESCRIPTION'] = only_use_column6.get_group(group)['n_des'] + ',' + only_use_column6.get_group(group)['ad_des']
    output_df['FILE'] = only_use_column6.get_group(group)['file']
    output_df['YOUTUBE'] = only_use_column6.get_group(group)['youtube']
    output_df['URL'] = only_use_column6.get_group(group)['url']
    
    output_df["NEW_DESC"] = output_df.apply(lambda x: descFormat(x['TITLE'],x['DESCRIPTION'],x['FILE'],x['YOUTUBE'],x['URL']), axis = 1)
    output.append(output_df)
    output_df.to_csv('output/6_hrm/group_id_'+str(group)+'.csv', index=False)

In [358]:
output[8]

,TITLE,DESCRIPTION,FILE,YOUTUBE,URL,NEW_DESC
132,ชื่อหน่วยงานใน สป. (อังกฤษ),NaN,nan,nan,nan,ชื่อหน่วยงานใน สป. (อังกฤษ)
133,ชื่อตำแหน่งสายงาน (อังกฤษ),NaN,download/article/menu/position_eng.pdf,nan,nan,ชื่อตำแหน่งสายงาน (อังกฤษ)
134,เครื่องราชอิสริยาภรณ์ และพระราชทานเพลิงศพ,NaN,nan,nan,nan,เครื่องราชอิสริยาภรณ์ และพระราชทานเพลิงศพ
135,เครื่องแบบของข้าราชการ ลูกจ้างประจำ และพนักงาน...,NaN,nan,nan,nan,เครื่องแบบของข้าราชการ ลูกจ้างประจำ และพนักงาน...
136,คลังความรู้,NaN,nan,nan,nan,คลังความรู้
137,คู่มือ (Manual),NaN,nan,nan,nan,คู่มือ (Manual)
138,บุคคลดีเด่นที่ได้รับการยกย่องและเชิดชูเกียรติ,NaN,nan,nan,nan,บุคคลดีเด่นที่ได้รับการยกย่องและเชิดชูเกียรติ
139,แผนบริหารทรัพยากรบุคคล,NaN,nan,nan,nan,แผนบริหารทรัพยากรบุคคล
140,เครื่องราชอิสริยาภรณ์ และพระราชทานเพลิงศพ,NaN,nan,nan,nan,เครื่องราชอิสริยาภรณ์ และพระราชทานเพลิงศพ
141,เครื่องแบบของข้าราชการ ลูกจ้างประจำ และพนักงาน...,NaN,nan,nan,nan,เครื่องแบบของข้าราชการ ลูกจ้างประจำ และพนักงาน...
142,บุคคลดีเด่นที่ได้รับการยกย่องและเชิดชูเกียรติ,NaN,nan,nan,nan,บุคคลดีเด่นที่ได้รับการยกย่องและเชิดชูเกียรติ

- get article detail first only